#!/bin/sh
# Generates ElabOp.lean (stdout) from the pinned toolchain's own Init
# sources: macro/binop% design spec § Harness (amended 2026-10-02).
# Whole files, verbatim except: `module`/`prelude`/`import` lines are
# removed and the `public`/`meta` modifiers dropped (module-system
# syntax a plain prelude file cannot carry). Run from the repo so elan
# resolves the pinned toolchain: `mise run fixtures:regen-elab-op`.
set -eu
SRC="$(lean --print-prefix)/src/lean"
strip() {
  sed -E \
    -e '/^module$/d' \
    -e '/^prelude( |$)/d' \
    -e '/^(public )?(meta )?import /d' \
    -e 's/^public (meta )?section/section/' \
    -e 's/^@\[expose\] (public )?section/section/' \
    -e 's/^(public meta|public|meta) (def|abbrev|instance|theorem|structure|class|inductive|opaque|axiom|macro|syntax|@\[|noncomputable|unsafe|partial|protected|private|set_option)/\2/' \
    "$1"
}
echo "-- GENERATED by gen_elab_op.sh from the pinned toolchain's Init sources."
echo "-- Do not edit: run \`mise run fixtures:regen-elab-op\`."
echo "prelude"
for f in Init/Prelude.lean Init/Coe.lean Init/Notation.lean; do
  echo "-- ===== $f ====="
  strip "$SRC/$f"
done
# Init/Notation.lean:592 opens `namespace Lean` and never closes it; without
# this the Core excerpts below land in `Lean` (kind `Lean.«term_↔_»`).
echo "end Lean"
echo "-- ===== Init/Core.lean excerpts: Iff (:188-197), bne (:772-777), Ne (:875-880) ====="
for r in 188,197 772,777 875,880; do
  sed -n "${r}p" "$SRC/Init/Core.lean"
done
